### ISSUE TITLE
Version 2.0 Roadmap

### ISSUE THREAD

**Issue by mominul** [OpenBangla/OpenBangla-Keyboard#101]
# Version 2.0 Roadmap
**This will be a breaking version change!**

- [x] Change binary names of `OpenBangla-Engine` and `OpenBangla-Keyboard` into `ibus-openbangla` and ~~`openbangla-keyboard`~~ `openbangla-gui` to match with the other ibus engines and unix programs. ~~But I am quite confused about naming `OpenBangla-Keyboard` or the frontend(GUI) as there are few binaries that have a minus(`-`) character in their names, should we choose a shorter name like `openbangla` or `obk`?~~ #103 
- [ ] Redesign the Layout viewer dialog with the support of zooming and SVG image.
- [ ] Redesign the About dialog box, cc @Adyel .
- [ ] A brand new website design!
- [ ] A new layout file format with compression enabled. This will also tackle #98 as this would need a breaking change.
- [ ]  Finish up writing libRiti.
- [ ] Show suggestions when writing with fixed layout methods. #61 

More to come :blush:

**Comment by mominul** [comment]
cc @Adyel @bdeshi

**Comment by Adyel** [comment]
@mominul  I think `openbangla` is better. `obk` is not easily understandable at first glance.

**Comment by bdeshi** [comment]
exciting!

I agree that `obk` is unintelligible. However, instead of just plain `openbangla`, how do you guys feel about `openbangla-gui`?
In case future versions include additional binaries, each can have descriptive functional names with `openbangla-` as base. You can have `openbangla-gui` for the gui, `openbangla-convert` for a binary that converts layout file formats, etc.
(Don't worry, there are countless binaries with hyphens in their name. systemd alone has [tens of those](https://archlinux.pkgs.org/rolling/archlinux-core-x86_64/systemd-242.29-1-x86_64.pkg.tar.xz.html#howto). )

**Comment by mominul** [comment]
@bdeshi Yes! `openbangla-gui` seems like to be a good replacement!

**Comment by Adyel** [comment]
I have created a milestone and project board for `Version 2.0`. Let's use those properly ✊ 🔀

**Comment by mominul** [comment]
Closing on behalf of https://github.com/OpenBangla/OpenBangla-Keyboard/projects/1
